### ISSUE TITLE
No api key in query

### ISSUE THREAD

**Issue by woeterman94** [Kurounin/ep_auth_session#4]
When using the iframe I get "No API key in Query"

**Comment by Kurounin** [comment]
@woeterman94 the plugin is meant to be used with an existing session id to display the etherpad-lite page, not to do api calls. You're supposed to use the api to create the session first (from a backend service) and then output an iframe as mentioned in the documentation of the plugin to display the etherpad-lite page.

**Comment by woeterman94** [comment]
I very much understand. Did you read my comment?
When I use the iframe, like demonstrated in your example.
`<iframe src="http://pad.test.de/auth_session?sessionID=SESSION_ID&padName=PAD_NAME" width="600" height="400"></iframe>
`
I get a white screen saying "No API key in Query"

**Comment by Kurounin** [comment]
Either something changed in recent versions of etherpad or it's related to your configuration. To debug the issue I would suggest opening your etherpad page (e.g. `http://pad.test.de/`) login with your account, open a pad (e.g. `PAD_NAME`) and check what your cookie contains.
It might be different from what the plugin is setting, which is `sessionID=SESSION_ID`.
Also can you tell me the pad url and all the params included?

**Comment by woeterman94** [comment]
Thanks for your reply and help. You were right, something was wrong with my configuration.

When I use 

`<iframe src="mypad/auth_session?sessionID=s.7f055826be4fbbd573954ec0580a4117&padName=test" width="600" height="400"></iframe>`

My cookie is correctly set. (session Id =s.7f055826be4fbbd573954ec0580a4117)

However the author name is always empty. Is this normal? 
(I created the session with the API and linked it) 

![image](https://user-images.githubusercontent.com/5755057/94823510-37f33c80-0404-11eb-856b-854ae6b42c67.png)


I'll take a more detailed look tomorrow.

**Comment by woeterman94** [comment]
It was a configuration mistake on my end indeed.

**Comment by Kurounin** [comment]
Glad you sorted it out.
