### ISSUE TITLE
Etherpad 1.8.9 doesn't start after installing ep_auth_session

### ISSUE THREAD

**Issue by pankajchejara23** [Kurounin/ep_auth_session#6]
I have been using ep_auth_session without any issue. Recently, I tried it on the etherpad 1.8.9. After installing the plugin, etherpad doesn't start. 
If I uninstall the plugin and start it again, it works fine.
Could you please help in resolving this issue.

After installing the plugin 

<img width="1402" alt="Screenshot 2021-02-24 at 17 35 29" src="https://user-images.githubusercontent.com/21138354/109024834-d1c6c900-76c6-11eb-8e36-a0ab9e669c5f.png">

This is after uninstalling the plugin (works perfectly)

<img width="1402" alt="Screenshot 2021-02-24 at 17 38 29" src="https://user-images.githubusercontent.com/21138354/109025193-2cf8bb80-76c7-11eb-8a30-91a5297310d3.png">

**Comment by JohnMcLear** [comment]
Please try it on 1.8.8, just to validate it's something that changed between 1.8.8 and 1.8.9 :)

**Comment by rhansen** [comment]
If you try with Etherpad 1.8.7 I'm guessing you'll see the following error in your logs:

> UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_auth_session, function name: ...registerRoute, hook: expressCreateServer): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior.

The future that the error message warned about is now. The bug hasn't been fixed, so Etherpad is freezing on startup.

Fortunately the fix is easy; see PR #7.

**Comment by Kurounin** [comment]
@pankajchejara23 Thank you for reporting this issue. Can you try version 1.0.9 of the plugin which includes @rhansen fix?
