### ISSUE TITLE
Pass given padOptions as GET parameters

### ISSUE THREAD

**Issue by thomashackl** [Kurounin/ep_auth_session#8]
When embedding a pad via iframe, you can set some padOptions as GET parameters in the iframe URL, like `showLineNumbers` or `showChat`. But after session authentication, the parameters are gone, as the plugin doesn't pass them on when redirecting to the actual pad. Only `padName`, `groupID` and `lang`are passed when given.

**Comment by Kurounin** [comment]
Hi @thomashackl . Thanks for the PR. Wouldn't it be simpler to keep the current query parameters, instead of using the `urlHelper` ?

**Comment by thomashackl** [comment]
Well... could be :) I can have another look at the code, you can change anything you want, too, of course. As mentioned in the PR, the code is based on luniki's work.

**Comment by Kurounin** [comment]
I published version 1.1.0. Can you please check it and let me know if there are any issues?

**Comment by thomashackl** [comment]
Looks good, i didn't register any issues so far. Thanks for merging!
